### ISSUE TITLE
[plugin-commonjs] Uncaught SyntaxError: Identifier 'react' has already been declared

### ISSUE THREAD

**Issue by ashubham** [rollup/plugins#392]
- Rollup Plugin Name: commonjs
- Rollup Plugin Version: master (unreleased)
- Rollup Version: 2.9.1
- Operating System (or Browser): OSX
- Node Version: 12.16.2

### How Do We Reproduce?

https://repl.it/@ashubham/rollup-duplicate-react-bug-1

### Expected Behavior

`React` should be imported and exported only once.

`output\Dog-<hash>.js` should have only one React import.

### Actual Behavior

`output\Dog-<hash>.js` has 2 React imports.
`import { R as react, r as react } from './index-329ab642.js';`

Causing this issue:

```
Uncaught SyntaxError: Identifier 'react' has already been declared
```

**Comment by csr632** [comment]
I have created a minimal repo:
https://github.com/csr632/rollup-issue/tree/cjs-bug

**Comment by danielgindi** [comment]
Please create a REPL that reproduces the problem so we can play with it. Also it would be better to use "simpler" modules, even ones that are created inside the REPL, so it will be easier to see the issue in the code.

**Comment by ashubham** [comment]
I posted this Repl where the issue is clearly reproducible:
https://repl.it/@ashubham/rollup-duplicate-react-bug-1

Please let me know if you need more details there.

**Comment by danielgindi** [comment]
Looks to me like a bug in `rollup` itself with resolving the names of imports/exports

**Comment by TrySound** [comment]
I just faced this issue after upgrading to rollup 2.10.5. Looks like the issue happens when default and named imports from react are used.
cc @lukastaegert

**Comment by jacksteamdev** [comment]
I can confirm this problem with rollup @ 2.7.6, 2.8.2, 2.9.1 and 2.10.5 & @rollup/plugin-commonjs@12.0.0

This bug is not present with rollup@2.10.5 & @rollup/plugin-commonjs@11.1.0

**Comment by danielgindi** [comment]
@jacksteamdev Have you tested with master? Because a lot of fixes did not get released yet.

**Comment by shellscape** [comment]
@danielgindi I released a new version yesterday.

**Comment by danielgindi** [comment]
I've just tested this with 12.0.0 - I don't see any issue.  

@jacksteamdev More than that - the Dog.js file in your code is pure ES code, no commonjs. Again, that file is *not* processed by the commonjs plugin. Which means that `rollup` gets confused with the names or deduping imports. A slight change in names in commonjs plugin (transforming 'react' dependency) might make all the difference, but it still means that there is some kind of bug in rollup itself.
This is why I asked for a REPL using a simpler module, not react. Reducing it to the simplest possible input that produces the bug in the output. This way we can investigate the issue in `rollup` itself.

Also note that in latest rollup versions - a lot of issues regarding the names chosen by rollup were fixed.

**Comment by csr632** [comment]
> I have created a reproduce repo:
> https://github.com/csr632/rollup-issue/tree/cjs-bug
> 
> Rollup Plugin Version:
> https://github.com/rollup/plugins/tree/fe037dbd59b0ee04c2de7b6b48c8cfcc98ccbcb6 (unreleased)
> 
> @danielgindi

My reproduce still show bug with latest rollup&plugins. After build, you can see two propTypes in `dist/index2.js`: `import { p as propTypes, P as propTypes } from './index-28f8696c.js';`
@danielgindi

**Comment by lukastaegert** [comment]
I have started to take a look at this and this is indeed solely an issue with Rollup itself. Here is a very condensed Rollup-only repro: https://repl.it/repls/MessyMurkyWatchdog

**Comment by lukastaegert** [comment]
Tentative fix at rollup/rollup#3586

**Comment by lukastaegert** [comment]
I can confirm that it solves the original repro posted here

**Comment by TrySound** [comment]
Thank you @lukastaegert!
