### ISSUE TITLE
Wrong complierOptions when tsconfig in cwd is extended from another tsconfig

### ISSUE THREAD

**Issue by meteorlxy** [rollup/plugins#70]
For example:

```json
{
  "extends": "../../tsconfig.base.json",
  "compilerOptions": {
    "rootDir": "./src",
    "outDir": "./dist",
    "declaration": false
  }
}
```

Seems that `rollup-plugin-typescript` does not try to resolve the base tsconfig, so that the `compilerOptions` is not extended.

**Comment by shellscape** [comment]
This should be fixed by https://github.com/rollup/rollup-plugin-typescript/pull/153, please let us know if it's not.

**Comment by cortopy** [comment]
@shellscape I don't think it's fixed. I'm getting

```
@rollup/plugin-typescript: Couldn't process compiler options
```

when using `extends: 'my-package` where 'my-package' is a module in my monorepo

**Comment by shellscape** [comment]
@NotWoods any thoughts?

**Comment by meteorlxy** [comment]
Uh it's not solved I think. So maybe I should open an issue in the new repo?

**Comment by NotWoods** [comment]
I'm going to reopen the issue and try to solve the failing use cases described here.

**Comment by slavafomin** [comment]
I can confirm that the issue is still present. @NotWoods @shellscape do you have any progress with this? Maybe there is a way to use TypeScript compiler API to actually process the config as `tsc` does?

**Comment by NotWoods** [comment]
Could you provide a REPL link with an example of what's failing? We are using the compiler APIs Typescript provides already. The upcoming 4.0.0 version should fix some more issues too.

**Comment by slavafomin** [comment]
Well, as others mentioned, I have a very simple setup with two `tsconfig.json` files, where one file is extending the other one. However, the compiler options are loaded only from the specified file. Options in the base config are getting totally ignored.

Are you using TypeScript compiler to load the config or are you loading it yourselves? I've tried to find a code that is responsible for loading `tsconfig.json` in `tsc` yesterday, but failed to do so due to the complexity and the size of the codebase. Could please you point me in the right direction if you are familiar with the codebase?

**Comment by NotWoods** [comment]
The examples in this issue all work now, so I would really appreciate the exact configuration you're using that doesn't work. I can't point to an exact location in the Typescript repo but we use the APIs provided by Typescript for parsing the configuration.

**Comment by slavafomin** [comment]
I would have been glad to assist with this issue further, but we have had to switch to the `rollup-plugin-typescript2` due to the lack of some critical features in this plugin. Sorry about that… 😢

**Comment by NotWoods** [comment]
Fixed in version 4.0.0 of the typescript plugin

**Comment by developer239** [comment]
@NotWoods Still not working 🙂`rollup-plugin-typescript2` works fine.

**Comment by iOiurson** [comment]
I'm getting a similar issue with version 5.0.2: `Couldn't process compiler options`. I had to switch to `rollup-plugin-typescript2` to solve the issue :/

**Comment by lake2** [comment]
same issue + 1
