### ISSUE TITLE
Error: [type] is not exported by [file]

### ISSUE THREAD

**Issue by Vehmloewff** [rollup/plugins#71]
_(This issue was transferred from rollup-plugin-typescript and had no issue template)_

This code:

```ts
import { Type1, Type2 } from './file.ts';

export {
	Type2
}

export const fn1: Type1 = () => {
	// ...
}
```

Throws this error in the console:

```
[!] Error: 'Type2' is not exported by src/file.ts
```

Is there any workaround or fix for this?

**Comment by ziofat** [comment]
Hi, is this fixed or not?

**Comment by NotWoods** [comment]
It's not fixed yet, it's just been transferred to the new repository.

**Comment by Vehmloewff** [comment]
There is a workaround for this, I'll be it is not an ideal one, but it is what I have been using in the meantime.

Instead of

```ts
import { Type1, Type2 } from './file.ts';

export {
	Type2
}

export const fn1: Type1 = () => {
	// ...
}
```

I just

```ts
import { Type1, Type2 } from './file';

export const fn1: Type1 = () => {
	// ...
}

export * from './file';
```

The only problem with this is that I do not really want to export `Type1`.  But in my case, I would rather have extra export that not have the ones I need.

**Comment by Vehmloewff** [comment]
I just realized that this is a duplicate of https://github.com/rollup/rollup-plugin-typescript/issues/28.  Sorry for the inconvenience.

**Comment by ziofat** [comment]
Well. You are referring to a issue in old repository and it was closed due to repository move. However this is not resolved right now. For me the workaround is not acceptable because I have a very large code base.
The `rollup-plugin-typescript2` handles this situation very well but it is really slow after upgrading to typescript 3.4.

**Comment by shellscape** [comment]
@ziofat if you'd like to put together a minimal reproduction in a repo that we can clone, I'd be happy to reopen this. We're going to need a reproduction to triage this.

**Comment by ziofat** [comment]
@shellscape OK, I will try to make a reproduction later.

**Comment by PeteJodo** [comment]
I created a repo that reproduces the issue here https://github.com/PeteJodo/repro-rollup-typescript-export-type-issue

I get this output

```
> repro-rollup-typescript-export-type-issue@1.0.0 rollup /Users/pjodogne/Projects/TEMP/repro-rollup-typescript-export-type-issue
> rollup -c


src/index.ts → dist/index.js...
[!] Error: 'IExample' is not exported by src/dep.ts
https://rollupjs.org/guide/en/#error-name-is-not-exported-by-module
src/index.ts (1:9)
1: export { IExample, MyExample } from './dep';
            ^
Error: 'IExample' is not exported by src/dep.ts
    at error (/Users/pjodogne/Projects/TEMP/repro-rollup-typescript-export-type-issue/node_modules/rollup/dist/rollup.js:5365:30)
    at Module.error (/Users/pjodogne/Projects/TEMP/repro-rollup-typescript-export-type-issue/node_modules/rollup/dist/rollup.js:9708:9)
    at handleMissingExport (/Users/pjodogne/Projects/TEMP/repro-rollup-typescript-export-type-issue/node_modules/rollup/dist/rollup.js:9625:21)
    at Module.getVariableForExportName (/Users/pjodogne/Projects/TEMP/repro-rollup-typescript-export-type-issue/node_modules/rollup/dist/rollup.js:9829:17)
    at Module.includeAllExports (/Users/pjodogne/Projects/TEMP/repro-rollup-typescript-export-type-issue/node_modules/rollup/dist/rollup.js:9876:35)
    at Promise.all.then (/Users/pjodogne/Projects/TEMP/repro-rollup-typescript-export-type-issue/node_modules/rollup/dist/rollup.js:13083:24)
    at <anonymous>
```

**Comment by weyert** [comment]
Yes, I have the same issue and temporary not exporting the props of my React components due to this issue. I have also tried `rollup-plugin-typescript2` but that's not working at all, keep getting `failed to transpile '/Users/work/experiment/src/index.ts'`  and have no idea what that is supposed to mean.

**Comment by shellscape** [comment]
@NotWoods this might be up your alley. @PeteJodo put together a reproduction repo for reference, and it might be related to the updates you have planned already.

**Comment by NotWoods** [comment]
I'll try to get this working with our larger TS plugin updates.

**Comment by NotWoods** [comment]
This is fixed with @rollup/plugin-typescript version 3.0.0!

**Comment by hasangenc0** [comment]
> @rollup/plugin-typescript
Hi, congrats to fix this bug 🎉.
When the new version will be released?

**Comment by earksiinni** [comment]
Can we reopen? I'm still receiving this error when using Babel to compile TypeScript.

**Comment by shellscape** [comment]
@earksiinni you're welcome to open a new issue with a proper reproduction. We won't be reopening this one.

**Comment by marcus13371337** [comment]
Solved this issue by doing the following:
`index.ts`
```ts
import { TypeYouWantToExport as TypeYouWantToExportReal } from './file1'

export type TypeYouWantToExport = TypeYouWantToExportReal
```

**Comment by kswope** [comment]
For desperate googlers: I'm a total rollup/typescript noob but I fixed it for myself with

https://www.typescriptlang.org/docs/handbook/modules.html#importing-types

**Comment by chrisrrowland** [comment]
> For desperate googlers: I'm a total rollup/typescript noob but I fixed it for myself with
> 
> https://www.typescriptlang.org/docs/handbook/modules.html#importing-types

This worked for me too (import _type_) but it does seem like a workaround.

**Comment by dayrlism10** [comment]
this resolved my concern, hope it helps

`export type MyType = import("./types.ts").MyType;`

**Comment by spadgeaki** [comment]
Hi, i had similar issue but with react-beautiful-dnd. It helped to `yarn install -D @types/react-beautiful-dnd`

**Comment by matthew-dean** [comment]
This also fails with `@rollup/plugin-sucrase` FYI

**Comment by mklueh** [comment]
Running into this with Nuxt 3.0.0-rc.4 when trying to import from a library, while it was previously working

**Comment by thorsent** [comment]
I ran into this issue when trying to use an enum that was exported by the library's typedef but which wasn't exported in the library's es6 module. There was no help from the compiler until switching from `import { Blah } from "blah"` to `import type { Blah } from "blah"`. Then the compiler barfed up the problem. I worked around the problem by just using the raw string, but there might be a magic sequence of tsconfig that would have helped.

**Comment by mw-sezzle** [comment]
@thorsent the suggestion to `import type ...` worked perfectly with a Vite build (which uses rollup). Thanks!

**Comment by boshoff** [comment]
> @thorsent the suggestion to `import type { Blah } from "blah"` worked perfectly with a Vite build (which uses rollup). Thanks!

In my case I was importing an `enum` so `import type` was preventing it from being used as a value.  Specifying that the module should remain [external](https://rollupjs.org/configuration-options/#external) to the bundle in `vite.config.js` resolved the issue:

```js
// ...

export default defineConfig({
  build: {
    rollupOptions: {
      external: ['@project/library'],
    },
  },
  // ...
})
```

**Comment by codeho** [comment]
> > @thorsent the suggestion to `import type { Blah } from "blah"` worked perfectly with a Vite build (which uses rollup). Thanks!
> 
> In my case I was importing an `enum` so `import type` was preventing it from being used as a value. Specifying that the module that I'm importing from should remain [external](https://rollupjs.org/configuration-options/#external) to the bundle in `vite.config.js` resolved the issue:
> 
> ```js
> // ...
> 
> export default defineConfig({
>   build: {
>     rollupOptions: {
>       external: ['@project/library'],
>     },
>   },
>   // ...
> })
> ```

this worked for me!

**Comment by D-Thrane** [comment]
Having same issue when I build in Vite. All my interfaces get the import/export error
